Correct the caching of the solidity compiler. (#3370)
## Motivation

The caching is not working for the solidity compiler `solc`. We correct
here the problem.

## Proposal

Correct the CI code in order to have the solc compiler.

## Test Plan

The CI.

## Release Plan

Not relevant.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -165,7 +165,9 @@ jobs:
     - uses: actions/checkout@v3
     - uses: actions-rust-lang/setup-rust-toolchain@v1
     - uses: foundry-rs/foundry-toolchain@v1.2.0
-    - name: Cache solc
+    - name: Ensure Solc Directory Exists
+      run: mkdir -p /home/runner/.solc
+    - name: Cache Solc
       id: cache-solc
       uses: actions/cache@v4
       with:
@@ -177,6 +179,14 @@ jobs:
       uses: pontem-network/get-solc@master
       with:
         version: v0.8.25
+    - name: Add Solc to PATH
+      run: echo "/home/runner/.solc" >> $GITHUB_PATH
+    - name: List the content of the Solc cache
+      run: ls /home/runner/.solc/v0.8.25/solc-static-linux
+    - name: Create a Solc symbolic link
+      run: ln -sf /home/runner/.solc/v0.8.25/solc-static-linux /home/runner/.solc/solc
+    - name: Check if Solc is in PATH
+      run: which solc || echo "Solc not found in PATH"
     - name: Install Protoc
       uses: arduino/setup-protoc@v1
       with:
@@ -188,7 +198,7 @@ jobs:
       run: |
         cargo test -p linera-ethereum --features ethereum
         cargo test test_wasm_end_to_end_ethereum_tracker --features ethereum,storage-service,unstable-oracles
-  
+
   storage-service-tests:
     runs-on: ubuntu-latest-16-cores
     timeout-minutes: 40
